### ISSUE TITLE
Sito DPC - Pagina non trovata 404

### ISSUE THREAD

**Issue by y-vasyunin** [pcm-dpc/DPC-Aggregati-Strutturali-ITH-NordEst#3]
Il link nella [descrizione del campo](https://github.com/pcm-dpc/DPC-Aggregati-Strutturali-ITH-NordEst#formato-degli-aggregati-strutturali) `IDAG` porta a una pagina non trovata.

**Comment by pierluigicara** [comment]
Grazie della segnalazione il link ora è stato adeguato.
